### ISSUE TITLE
3.0.0

### ISSUE THREAD

**Issue by SimplyCorey** [SimpleSoftwareIO/simple-qrcode#127]
Outlining our plans to release Simple-QrCode 3.0.

- [x] Update dependencies (#101 #100)
- [x] Enable Background Transparency (#38)
- [x] Allow for "fancy" QrCodes (#69)
- [x] Fix Margin use cases (#85)
- [x] Determine and solve issue related to white squares (#99)
- [ ] Allow for the image location to be moved around the QrCode (#112)
- [ ] Add new Helpers; Calendar, Ether, others (#116)
- [x] Improve function with inserting QrCode into a blade email (#132)
- [x] Resolve issue with image overlay and URL with larger overlay (#102)
- [x] Resolve strange scaling issues when combined with size (#152)
- [x] Switch to GitHub actions instead of Travis CI
- [ ] Update Docs

**Comment by jpcodeforit** [comment]
when you are going to release 3.0.0?.
Thanks for the library

**Comment by SimplyCorey** [comment]
@codetestmg I plan on working on it shortly.  The issue is always time balancing all over life activities and workload.  

Your welcome 👍
